name: Panorama on Azure

label: 2 - Deploy Panorama

description: |
  Deploy Panorama with optional HA

type: python3

labels:
  order: 2
  collection:
    - Azure Reference Architecture Skillet Modules

variables:
  - name: DEPLOYMENT_NAME
    description: Prefix for deployment
    default: ""
    type_hint: hidden
  - name: PASSWORD
    description: Admin Password
    type_hint: hidden
  - name: AZURE_REGION
    description: What Azure region do you want to deploy into?
    type_hint: dropdown
    dd_list:
      - key: '(US) Central US'
        value: 'centralus'
      - key: '(US) East US'
        value: 'eastus'
      - key: '(US) East US 2'
        value: 'eastus2'
      - key: '(US) North Central US'
        value: 'northcentralus'
      - key: '(US) South Central US'
        value: 'southcentralus'
      - key: '(US) West US'
        value: 'westus'
      - key: '(US) West US 2'
        value: 'westus2'
      - key: '(US) West Central US'
        value: 'westcentralus'
      - key: '(Canada) Canada Central'
        value: 'canadacentral'
      - key: '(Canada) Canada East'
        value: 'canadaeast'
      - key: '(South America) Brazil South'
        value: 'brazilsouth'
      - key: '(Europe) France Central'
        value: 'francecentral'
      - key: '(Europe) France South'
        value: 'francesouth'
      - key: '(Europe) Germany North'
        value: 'germanynorth'
      - key: '(Europe) Germany West Central'
        value: 'germanywestcentral'
      - key: '(Europe) North Europe'
        value: 'northeurope'
      - key: '(Europe) Norway East'
        value: 'norwayeast'
      - key: '(Europe) Norway West'
        value: 'norwaywest'
      - key: '(Europe) Switzerland North'
        value: 'switzerlandnorth'
      - key: '(Europe) Switzerland West'
        value: 'switzerlandwest'
      - key: '(Europe) UK South'
        value: 'uksouth'
      - key: '(Europe) UK West'
        value: 'ukwest'
      - key: '(Europe) West Europe'
        value: 'westeurope'
      - key: '(Middle East) UAE Central'
        value: 'uaecentral'
      - key: '(Middle East) UAE North'
        value: 'uaenorth'
      - key: '(Africa) South Africa North'
        value: 'southafricanorth'
      - key: '(Africa) South Africa West'
        value: 'southafricawest '
      - key: '(Asia Pacific) Australia East'
        value: 'australiaeast'
      - key: '(Asia Pacific) Southeast Asia'
        value: 'southeastasia'
      - key: '(Asia Pacific) Central India'
        value: 'centralindia'
      - key: '(Asia Pacific) South India'
        value: 'southindia'
      - key: '(Asia Pacific) West India'
        value: 'westindia'
      - key: '(Asia Pacific) East Asia'
        value: 'eastasia'
      - key: '(Asia Pacific) Japan East'
        value: 'japaneast'
      - key: '(Asia Pacific) Japan West'
        value: 'japanwest'
      - key: '(Asia Pacific) Korea Central'
        value: 'koreacentral'
      - key: '(Asia Pacific) Korea South'
        value: 'koreasouth'
      - key: '(Asia Pacific) Australia Central'
        value: 'australiacentral'
      - key: '(Asia Pacific) Australia Central 2'
        value: 'australiacentral2'
      - key: '(Asia Pacific) Australia Southeast'
        value: 'australiasoutheast'
  - name: vpc_cidr_block
    description: CIDR block for the Management VNet. Code supports a /16 mask through /29
    default: 10.255.0.0/16
    type_hint: cidr
  - name: specify_network
    description: Do you want to define the network you will access Panorama from manually?
    type_hint: dropdown
    dd_list:
      - key: 'No: auto-discover my IP address'
        value: 'auto'
      - key: 'Yes: define the network and mask manually'
        value: 'manual'
  - name: onprem_cidr_block
    description: The network and mask (ex:/24) you will access Panorama from
    tyoe_hint: cidr
    toggle_hint:
      source: specify_network
      value: 'manual' 
  - name: enable_ha
    description: High-availability deployment option
    type_hint: dropdown
    dd_list:
      - key: A single Panorama
        value: 'false'
      - key: A high-availability pair
        value: 'true'
  - name: Init
    description: Deploy or destroy the environment
    default: ip_address
    type_hint: dropdown
    dd_list:
      - key: 'Deploy'
        value: "apply"
      - key: 'Destroy'
        value: 'destroy'

snippets:
  - name: script
    file: deploy_panorama.py
    input_type: env



